apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
    - image: asraralbeshri/reverseproxy
      name: reverseproxy
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "102Mi"
          cpu: "500m"
      ports:
      - containerPort: 8080
      command: ["/bin/sh", "-ec", "sleep 1000"]
  restartPolicy: Always